// frontend/src/components/Navbar.vue
<template>
    <div class="navbar">
        <router-link to="/">Home</router-link>
        <router-link v-if="!loggedIn" to="/login">Login</router-link>
        <router-link v-if="!loggedIn" to="/register">Register</router-link>
        <router-link v-if="loggedIn" to="/profile">Profile</router-link>
        <router-link v-if="loggedIn" to="/login" @click="handleLogout" >Logout</router-link>
    </div>
</template>
<script setup>
    import { ref, defineProps } from 'vue';
    import { useRouter } from 'vue-router';

    const props = defineProps({
        loggedIn: Boolean
    })

    const router = useRouter()
    const loggedIn = ref(props.loggedIn)

    const handleLogout = () =>{
        localStorage.removeItem('token');
        loggedIn.value = false
        router.push('/login')
    }
</script>

// frontend/src/components/Navbar.jsx
import React from "react";
import { Link } from "react-router-dom";

const Navbar = ({ loggedIn, handleLogout }) => {

    return (
        <div className="navbar">
            <Link to="/">Home</Link>
            <Link to="/">Products</Link>
            {!loggedIn && <Link to="/login">Login</Link>}
            {!loggedIn && <Link to="/register">Register</Link>}
            {loggedIn && <Link to="/profile">Profile</Link>}
            {loggedIn && <Link to="/logout" onClick={handleLogout}>Logout</Link>}
        </div>
    )
}
export default Navbar;
