// frontend/src/components/Navbar.vue
<template>
    <div class="navbar">
        <router-link to="/">Home</router-link>
        <router-link v-if="!loggedIn" to="/login">Login</router-link>
        <router-link v-if="!loggedIn" to="/register">Register</router-link>
        <router-link v-if="loggedIn" to="/profile">Profile</router-link>
        <router-link v-if="loggedIn" to="/login" @click="handleLogout" >Logout</router-link>
    </div>
</template>
<script setup>
    import { ref, defineProps } from 'vue';
    import { useRouter } from 'vue-router';

    const props = defineProps({
        loggedIn: Boolean
    })

    const router = useRouter()
    const loggedIn = ref(props.loggedIn)

    const handleLogout = () =>{
        localStorage.removeItem('token');
        loggedIn.value = false
        router.push('/login')
    }
</script>

// frontend/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  loggedIn: boolean = false;

  constructor(private apiService: ApiService, private router:Router) {
    this.checkIfLoggedIn()
  }

  ngOnInit(): void {
    this.apiService.refresh.subscribe(()=>{
      this.checkIfLoggedIn();
    })
  }

  checkIfLoggedIn(){
    const token = localStorage.getItem('token')
    if (token) {
      this.loggedIn = true
    }else{
      this.loggedIn = false;
    }
  }
  logout(): void{
    this.loggedIn = false;
    localStorage.removeItem('token')
    this.router.navigate(['/login'])
  }

}

<div class="navbar">
    <a routerLink="/">Home</a>
    <a *ngIf="!loggedIn" [routerLink]="['/login']">Login</a>
    <a *ngIf="!loggedIn" [routerLink]="['/register']">Register</a>
    <a *ngIf="loggedIn" [routerLink]="['/profile']">Profile</a>
    <a *ngIf="loggedIn" [routerLink]="['/logout']" (click)="logout()">Logout</a>
</div>
