// frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  error: string = '';
  username: string = ''
  password: string = ''
  constructor(private apiService: ApiService, private router: Router) { }

  ngOnInit(): void {
  }
  login(): void {
    if (this.username == '' || this.password == '') {
      this.showError("Please all fields are required")
      return;
    }

    this.apiService.login({username: this.username, password: this.password}).subscribe({
      next:(response: any)=>{
        const token = response.token
        console.log("Login Token:", token)
        localStorage.setItem('token', token)
        this.apiService.triggerRefresh();
        this.router.navigate(['/profile'])
      },
      error: (error: any)=>{
        console.log(error)
        this.showError(error.error?.message || "Login Failed");
      }
    })
  }

  private showError(errMes: string): void {
    this.error = errMes;
    setTimeout(()=>{
      this.error = ''
    }, 3000)
  }
}


<div class="login-container">
    <h2>Login Page</h2>
    <p *ngIf="error" class="error-message">{{ error }}</p>
    <form (submit)="login()">
        <input [(ngModel)]="username" name="username" type="text" required placeholder="Username" />
        <br />
        <input [(ngModel)]="password" name="password" type="password" required placeholder="Password" />
        <br />
        <button type="submit">Login</button>
    </form>
    <p>
        Don't have an account? <a routerLink="/register">Register</a>
    </p>
</div>

// frontend/src/components/auth/Login.jsx
import React, { useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";


const Login = () => {
    const navigate = useNavigate();
    const [error, setError] = useState('')

    const [formData, setFormData] = useState({
        username: '',
        password: ''
    })

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData((prevData) => ({
            ...prevData,
            [name]: value,
        }))
    }


    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:5500/login', formData);
            const { token } = response.data;
            console.log("Login Token is: " + token)
            localStorage.setItem('token', token);
            setError('')
            navigate('/profile')

        } catch (error) {
            console.log("Login Failed: " + error)
            setError(error.response.data.message)
            setTimeout(() => {
                setError('');
            }, 3000);
        }
    }

    return (
        <div className="login-container">
            <h2>Login Page</h2>
            {error && <p style={{color: 'red'}}>{error}</p>}
            <form onSubmit={handleSubmit}>
                <input type="text" name="username"
                    value={formData.username} onChange={handleChange}
                    required placeholder="Username" /> <br />

                <input type="password" name="password"
                    value={formData.password} onChange={handleChange}
                    required placeholder="Password" /> <br />
                <button type="submit">Login</button>
            </form>
            <p>Don't have an account? <Link to='/register'>Login</Link></p>
        </div>
    )
}
export default Login;
