// frontend/src/views/Login.vue
<template>
    <div class="login-container">
      <h2>Login Page</h2>
      <p v-if="error" class="error-message">{{ error }}</p>
      <form @submit.prevent="login">
          <input v-model="username" required  placeholder="Enter Your Username"/>
          <input v-model="password" type="password" required placeholder="Enter Your Password" />
        <button type="submit">Login</button>
      </form>
      <p>Don't have an account? <router-link to="/register">Register</router-link></p>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  import {handleLogin} from '../services/apiService';
  
  const router = useRouter();
  const username = ref('');
  const password = ref('');
  const error = ref('');
  
  const login = async () => {
    try {
      const response = await handleLogin(username.value, password.value );
      const { token } = response.data;
  
      console.log('Login successful', response.data);
  
      // Save the token to localStorage
      localStorage.setItem('token', token);
  
      // Redirect to profile page
      router.push('/profile');
    } catch (error) {
      console.error('Login failed', error.response?.data.message || 'An unexpected error occurred');
      showError(error.response?.data.message || 'An unexpected error occurred');
    }
  };
  
  const showError = (errorMessage) => {
    error.value = errorMessage;
  
    // Clear the error message after 5 seconds
    setTimeout(() => {
      error.value = '';
      username.value = ''
      password.value = ''
    }, 3000);
  };
  </script>

// frontend/src/components/auth/Login.jsx
import React, { useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";


const Login = () => {
    const navigate = useNavigate();
    const [error, setError] = useState('')

    const [formData, setFormData] = useState({
        username: '',
        password: ''
    })

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData((prevData) => ({
            ...prevData,
            [name]: value,
        }))
    }


    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:5500/login', formData);
            const { token } = response.data;
            console.log("Login Token is: " + token)
            localStorage.setItem('token', token);
            setError('')
            navigate('/profile')

        } catch (error) {
            console.log("Login Failed: " + error)
            setError(error.response.data.message)
            setTimeout(() => {
                setError('');
            }, 3000);
        }
    }

    return (
        <div className="login-container">
            <h2>Login Page</h2>
            {error && <p style={{color: 'red'}}>{error}</p>}
            <form onSubmit={handleSubmit}>
                <input type="text" name="username"
                    value={formData.username} onChange={handleChange}
                    required placeholder="Username" /> <br />

                <input type="password" name="password"
                    value={formData.password} onChange={handleChange}
                    required placeholder="Password" /> <br />
                <button type="submit">Login</button>
            </form>
            <p>Don't have an account? <Link to='/register'>Login</Link></p>
        </div>
    )
}
export default Login;
