// frontend/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  products: any[] = [];

  constructor(private apiService: ApiService) { }

  ngOnInit(): void {
    this.fetchProducts();
  }

  fetchProducts(): void{
    this.apiService.getProducts().subscribe({
      next:(response: any) =>{
        this.products = response
      },
      error: (error: any) =>{
        console.log("Error Fetching Products: " + error)
      }
    })
  }

}

<div class="home-container">
    <h2>Explore Our Products</h2>
    <div class="product-list" *ngIf="products.length > 0; else noProducts">
        <div *ngFor="let product of products" class="product-item">
            <h3>{{ product.name }}</h3>
            <p>{{ product.description }}</p>
            <p class="amount">Amount: ${{ product.amount }}</p>
        </div>
    </div>
    <ng-template #noProducts>
        <p>No products available.</p>
    </ng-template>
</div>

// frontend/src/views/Home.vue
<template>
    <div class="home-container">
        <h2>Explore Our Products</h2>
        <div class="product-list" v-if="products.length > 0">
            <div v-for="product in products" :key="product.id" class="product-item">
                <h3>{{ product.name }}</h3>
                <p>{{ product.description }}</p>
                <p class="amount">Amount: {{ product.amount }}</p>
            </div>
        </div>
        <div v-else>
            <p>No products available.</p>
        </div>
    </div>
</template>
  
<script setup>
import { ref, onMounted } from 'vue';
import { handleGetProducts } from '../services/apiService';

const products = ref([]);

onMounted(
    async () => {
        try {
            const response = await handleGetProducts('/products');
            products.value = response.data;
        } catch (error) {
            console.error('Error fetching products', error);
        }
    });
</script>
