// frontend/src/components/auth/Profile.jsx
import React, { useState, useEffect } from "react";
import axios from "axios";

const Profile = () => {

    const [userData, setUserData] = useState(null)

    useEffect(() => {

        const fetchUserDate = async () => {
            try {
                const response = await axios.get('http://localhost:5500/profile', {
                    headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
                });
                setUserData(response.data);
            } catch (err) {
                console.log('Error Fetching user profile data: ' + err)
            }
        }

        fetchUserDate();
    }, [])



    return (
        <div className="profile-container">

            {
                userData ? (
                    <div>
                        <h2>Your User name is: {userData.username}</h2>
                    </div>
                ) : (
                    <p>Loading user data</p>
                )
            }

        </div>
    )
}
export default Profile;

// frontend/src/views/Profile.vue
<template>
    <div>
      <h2>Profile Page</h2>
      <p v-if="error" style="color: red;">{{ error }}</p>
      <div v-if="user">
        <p>Welcome, <b>{{ user.username }}!</b></p>
        <p> We are happy to have you here 😁</p>
        <!-- Display other user details as needed -->
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  import {handleGetProfile} from '../services/apiService';
  
  const user = ref(null);
  const error = ref(null);
  
  onMounted(async () => {
    try {
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` }
      const response = await handleGetProfile(headers);
      console.log(response.data)
      user.value = response.data;
    } catch (err) {
      console.error('Error fetching user profile', err);
      error.value = 'Error fetching user profile. Please try again.' + err;
    }
  });
  </script>
  
  <style scoped>
  div {
    text-align: center;
    font-size: larger;
  }
  
  b {
    color: blue;
  }
  </style>
