// frontend/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  username: string = ''

  constructor(private apiService: ApiService) { }

  ngOnInit(): void {
    this.getUsername();
  }

  getUsername():void{
    const token = localStorage.getItem('token');
    console.log("Token is: " + token)
    const header:any = {headers: {Authorization:`Bearer ${token}`}}
    this.apiService.getProfileDetails(header).subscribe({
      next:(response: any)=>{
        console.log(response.username)
        this.username = response.username
      },
      error:(error: any)=>{
        this.username = error?.error.message || "An Unrecognized error occured";
      }
    })
  }

}


<div>
    <h2>Profile Page</h2>
    <div>
        <p>Welcome, <b>{{username }}!</b></p>
        <p> We are happy to have you here 😁</p>
        <!-- Display other user details as needed -->
    </div>
</div>

// frontend/src/views/Profile.vue
<template>
    <div>
      <h2>Profile Page</h2>
      <p v-if="error" style="color: red;">{{ error }}</p>
      <div v-if="user">
        <p>Welcome, <b>{{ user.username }}!</b></p>
        <p> We are happy to have you here 😁</p>
        <!-- Display other user details as needed -->
      </div>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  import {handleGetProfile} from '../services/apiService';
  
  const user = ref(null);
  const error = ref(null);
  
  onMounted(async () => {
    try {
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` }
      const response = await handleGetProfile(headers);
      console.log(response.data)
      user.value = response.data;
    } catch (err) {
      console.error('Error fetching user profile', err);
      error.value = 'Error fetching user profile. Please try again.' + err;
    }
  });
  </script>
  
  <style scoped>
  div {
    text-align: center;
    font-size: larger;
  }
  
  b {
    color: blue;
  }
  </style>
