// frontend/src/components/auth/Register.jsx
import React, { useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";

const Register = () => {
    const navigate = useNavigate();

    const [formData, setFormData] = useState({
        username: '',
        password: ''
    })

    const handleChange = (e) =>{
        const {name, value} = e.target;
        setFormData((prevData)=>({
            ...prevData,
            [name]: value,
        }))
    }


    const handleSubmit = async(e) =>{
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:5500/register',formData );
            console.log("Registration Successful")
            navigate('/login')
        } catch (error) {
            console.log("Registration Failed: " + error)
        }
    }


    return (
        <div className="registration-container">
            <h2>Registration Page</h2>
            <form onSubmit={handleSubmit}>
                <input type="text" name="username"
                    value={formData.username} onChange={handleChange}
                    required placeholder="Enter Username" /> <br />

                <input type="password" name="password"
                    value={formData.password} onChange={handleChange}
                    required placeholder="Enter Password" /> <br />
                <button type="submit">Register</button>
            </form>
            <p>Already have an account? <Link to='/login'>Login</Link></p>
        </div>
    )
}
export default Register;

// frontend/src/views/Register.vue
<template>
    <div class="registration-container">
      <h2>Registration Page</h2>
      <p v-if="error" class="error-message">{{ error }}</p>
      <form @submit.prevent="register">
          <input v-model="username" required placeholder="Enter Username" />
          <input v-model="password" type="password" required placeholder="Enter Username" />
        <button type="submit">Register</button>
      </form>
      <p>Already have an account? <router-link to="/login">Login</router-link></p>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  import {handleRegister} from '../services/apiService';
  
  const router = useRouter();
  const username = ref('');
  const password = ref('');
  const error = ref('');
  
  const register = async () => {
    try {
      const response = await handleRegister(username.value, password.value );
      console.log('Registration successful', response.data);
      router.push('/login');
    } catch (error) {
      console.error('Registration failed', error.response?.data || 'An unexpected error occurred');
      showError(error.response?.data.message || 'Registration failed');
    }
  };
  
  const showError = (errorMessage) => {
    error.value = errorMessage;
  
    // Clear the error message after 5 seconds
    setTimeout(() => {
      error.value = '';
      username.value = ''
      password.value = ''
    }, 3000);
  };
  </script>
