// frontend/src/views/Register.vue
<template>
    <div class="registration-container">
      <h2>Registration Page</h2>
      <p v-if="error" class="error-message">{{ error }}</p>
      <form @submit.prevent="register">
          <input v-model="username" required placeholder="Enter Username" />
          <input v-model="password" type="password" required placeholder="Enter Username" />
        <button type="submit">Register</button>
      </form>
      <p>Already have an account? <router-link to="/login">Login</router-link></p>
    </div>
  </template>
  
  <script setup>
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  import {handleRegister} from '../services/apiService';
  
  const router = useRouter();
  const username = ref('');
  const password = ref('');
  const error = ref('');
  
  const register = async () => {
    try {
      const response = await handleRegister(username.value, password.value );
      console.log('Registration successful', response.data);
      router.push('/login');
    } catch (error) {
      console.error('Registration failed', error.response?.data || 'An unexpected error occurred');
      showError(error.response?.data.message || 'Registration failed');
    }
  };
  
  const showError = (errorMessage) => {
    error.value = errorMessage;
  
    // Clear the error message after 5 seconds
    setTimeout(() => {
      error.value = '';
      username.value = ''
      password.value = ''
    }, 3000);
  };
  </script>

// frontend/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  error: string = '';
  username: string = ''
  password: string = ''

  constructor(private apiService: ApiService, private router: Router) { }

  ngOnInit(): void {
  }
  register(): void {
    if (this.username == '' || this.password == '') {
      this.showError("Please all fields are required")
      return;
    }

    this.apiService.register({username: this.username, password: this.password}).subscribe({
      next:(response: any)=>{
        const regRes = response.message
        console.log("Registeation Message:", regRes)
        this.router.navigate(['/login'])
      },
      error: (error: any)=>{
        console.log(error)
        this.showError(error.response?.data.message || "Registration Failed");
      }
    })
  }




  private showError(errMes: string): void {
    this.error = errMes;
    setTimeout(()=>{
      this.error = ''
    }, 3000)
  }
}

<div class="registration-container">
    <h2>Registration Page</h2>
    <p *ngIf="error" class="error-message">{{ error }}</p>
    <form (submit)="register()">
        <input [(ngModel)]="username" name="username" type="text" required placeholder="Enter Username" />
        <br />
        <input [(ngModel)]="password" name="password" type="password" required placeholder="Enter Password" />
        <br />
      <button type="submit">Register</button>
    </form>
    <p>Already have an account? <a routerLink="/login">Login</a></p>
</div>
